spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: AA
    password: aaproject12!
    url: jdbc:mysql://localhost:3308/a_a
    hikari:
      username: AA
      password: aaproject12!
      maximum-pool-size: 10
    #url: jdbc:mysql://127.0.0.1:3308/a_a
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  session:
    store-type: redis
    timeout: 1800
  redis:
    host: localhost
    #host: localhost
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
naver:
  client-id: K2z_KcKVvXcWpDWRsP54
  client-secret: wZhQIH_kGw


